[theme]
primaryColor = "#ef4f5f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f8f8"
textColor = "#1c1c1c"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
